#ifndef SOFTWARE_RENDERER_C_CONSTANTS_H
#define SOFTWARE_RENDERER_C_CONSTANTS_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define FOV 70
#define NEAR_PLANE 1.0
#define FAR_PLANE 100.0
#define AMBIENT_LIGHT_INTENSITY 0.2f

#endif //SOFTWARE_RENDERER_C_CONSTANTS_H